baseURL = "https://hblitza.github.io/MapProxy_Workshop_Praxiseinsatz/"
languageCode = "de-de"
title = "im Praxiseinsatz"

[params]
BookTheme = 'light'
BookLogo = './img/mapproxy.png'
BookToc = false
custom_css = ['assets/custom.css']
BookMenuBundle = '/menu'
